// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public final class FarmServiceImpl {
  private FarmServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_WaterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_WaterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_WaterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_WaterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_PriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_PriceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_PriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_PriceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_SwitchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_SwitchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_SwitchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_SwitchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\004farm\"\026\n\007Request\022\013\n\003day\030" +
      "\001 \001(\t\"#\n\021CalculateResponse\022\016\n\006result\030\001 \001" +
      "(\005\" \n\rWaterResponse\022\017\n\007message\030\001 \001(\t\"(\n\014" +
      "WaterRequest\022\013\n\003min\030\002 \001(\005\022\013\n\003max\030\003 \001(\005\"A" +
      "\n\014PriceRequest\022\017\n\007animal1\030\001 \001(\t\022\017\n\007anima" +
      "l2\030\002 \001(\t\022\017\n\007animal3\030\003 \001(\t\"\037\n\rPriceRespon" +
      "se\022\016\n\006result\030\001 \001(\005\"/\n\rSwitchRequest\022\016\n\006s" +
      "ensor\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\"D\n\016SwitchRes" +
      "ponse\022\020\n\010response\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022" +
      "\020\n\010previous\030\003 \001(\t2\364\001\n\013FarmService\0225\n\tcal" +
      "culate\022\r.farm.Request\032\027.farm.CalculateRe" +
      "sponse\"\000\0224\n\005level\022\022.farm.WaterRequest\032\023." +
      "farm.WaterResponse\"\0000\001\0229\n\ntotalPrice\022\022.f" +
      "arm.PriceRequest\032\023.farm.PriceResponse\"\000(" +
      "\001\022=\n\nirrigation\022\023.farm.SwitchRequest\032\024.f" +
      "arm.SwitchResponse\"\000(\0010\001B*\n\025com.smartfar" +
      "ming.farmB\017FarmServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_farm_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_farm_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_Request_descriptor,
        new java.lang.String[] { "Day", });
    internal_static_farm_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_farm_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_farm_WaterResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_farm_WaterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_WaterResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_farm_WaterRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_farm_WaterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_WaterRequest_descriptor,
        new java.lang.String[] { "Min", "Max", });
    internal_static_farm_PriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_farm_PriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_PriceRequest_descriptor,
        new java.lang.String[] { "Animal1", "Animal2", "Animal3", });
    internal_static_farm_PriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_farm_PriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_PriceResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_farm_SwitchRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_farm_SwitchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_SwitchRequest_descriptor,
        new java.lang.String[] { "Sensor", "Status", });
    internal_static_farm_SwitchResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_farm_SwitchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_SwitchResponse_descriptor,
        new java.lang.String[] { "Response", "Status", "Previous", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
