// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public interface PriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.PriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string animal1 = 1;</code>
   */
  java.lang.String getAnimal1();
  /**
   * <code>string animal1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnimal1Bytes();

  /**
   * <code>string animal2 = 2;</code>
   */
  java.lang.String getAnimal2();
  /**
   * <code>string animal2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getAnimal2Bytes();

  /**
   * <code>string animal3 = 3;</code>
   */
  java.lang.String getAnimal3();
  /**
   * <code>string animal3 = 3;</code>
   */
  com.google.protobuf.ByteString
      getAnimal3Bytes();
}
