// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public interface PriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.PriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();
}
