// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

/**
 * Protobuf type {@code farm.PriceRequest}
 */
public  final class PriceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:farm.PriceRequest)
    PriceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceRequest.newBuilder() to construct.
  private PriceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceRequest() {
    animal1_ = "";
    animal2_ = "";
    animal3_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PriceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            animal1_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            animal2_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            animal3_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartfarming.farm.FarmServiceImpl.internal_static_farm_PriceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartfarming.farm.FarmServiceImpl.internal_static_farm_PriceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartfarming.farm.PriceRequest.class, com.smartfarming.farm.PriceRequest.Builder.class);
  }

  public static final int ANIMAL1_FIELD_NUMBER = 1;
  private volatile java.lang.Object animal1_;
  /**
   * <code>string animal1 = 1;</code>
   */
  public java.lang.String getAnimal1() {
    java.lang.Object ref = animal1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      animal1_ = s;
      return s;
    }
  }
  /**
   * <code>string animal1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAnimal1Bytes() {
    java.lang.Object ref = animal1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      animal1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANIMAL2_FIELD_NUMBER = 2;
  private volatile java.lang.Object animal2_;
  /**
   * <code>string animal2 = 2;</code>
   */
  public java.lang.String getAnimal2() {
    java.lang.Object ref = animal2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      animal2_ = s;
      return s;
    }
  }
  /**
   * <code>string animal2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAnimal2Bytes() {
    java.lang.Object ref = animal2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      animal2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANIMAL3_FIELD_NUMBER = 3;
  private volatile java.lang.Object animal3_;
  /**
   * <code>string animal3 = 3;</code>
   */
  public java.lang.String getAnimal3() {
    java.lang.Object ref = animal3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      animal3_ = s;
      return s;
    }
  }
  /**
   * <code>string animal3 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAnimal3Bytes() {
    java.lang.Object ref = animal3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      animal3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAnimal1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, animal1_);
    }
    if (!getAnimal2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, animal2_);
    }
    if (!getAnimal3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, animal3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAnimal1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, animal1_);
    }
    if (!getAnimal2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, animal2_);
    }
    if (!getAnimal3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, animal3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartfarming.farm.PriceRequest)) {
      return super.equals(obj);
    }
    com.smartfarming.farm.PriceRequest other = (com.smartfarming.farm.PriceRequest) obj;

    boolean result = true;
    result = result && getAnimal1()
        .equals(other.getAnimal1());
    result = result && getAnimal2()
        .equals(other.getAnimal2());
    result = result && getAnimal3()
        .equals(other.getAnimal3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ANIMAL1_FIELD_NUMBER;
    hash = (53 * hash) + getAnimal1().hashCode();
    hash = (37 * hash) + ANIMAL2_FIELD_NUMBER;
    hash = (53 * hash) + getAnimal2().hashCode();
    hash = (37 * hash) + ANIMAL3_FIELD_NUMBER;
    hash = (53 * hash) + getAnimal3().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartfarming.farm.PriceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartfarming.farm.PriceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartfarming.farm.PriceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartfarming.farm.PriceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartfarming.farm.PriceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code farm.PriceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:farm.PriceRequest)
      com.smartfarming.farm.PriceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartfarming.farm.FarmServiceImpl.internal_static_farm_PriceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartfarming.farm.FarmServiceImpl.internal_static_farm_PriceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartfarming.farm.PriceRequest.class, com.smartfarming.farm.PriceRequest.Builder.class);
    }

    // Construct using com.smartfarming.farm.PriceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      animal1_ = "";

      animal2_ = "";

      animal3_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartfarming.farm.FarmServiceImpl.internal_static_farm_PriceRequest_descriptor;
    }

    @java.lang.Override
    public com.smartfarming.farm.PriceRequest getDefaultInstanceForType() {
      return com.smartfarming.farm.PriceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartfarming.farm.PriceRequest build() {
      com.smartfarming.farm.PriceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartfarming.farm.PriceRequest buildPartial() {
      com.smartfarming.farm.PriceRequest result = new com.smartfarming.farm.PriceRequest(this);
      result.animal1_ = animal1_;
      result.animal2_ = animal2_;
      result.animal3_ = animal3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartfarming.farm.PriceRequest) {
        return mergeFrom((com.smartfarming.farm.PriceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartfarming.farm.PriceRequest other) {
      if (other == com.smartfarming.farm.PriceRequest.getDefaultInstance()) return this;
      if (!other.getAnimal1().isEmpty()) {
        animal1_ = other.animal1_;
        onChanged();
      }
      if (!other.getAnimal2().isEmpty()) {
        animal2_ = other.animal2_;
        onChanged();
      }
      if (!other.getAnimal3().isEmpty()) {
        animal3_ = other.animal3_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartfarming.farm.PriceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartfarming.farm.PriceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object animal1_ = "";
    /**
     * <code>string animal1 = 1;</code>
     */
    public java.lang.String getAnimal1() {
      java.lang.Object ref = animal1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animal1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string animal1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnimal1Bytes() {
      java.lang.Object ref = animal1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animal1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string animal1 = 1;</code>
     */
    public Builder setAnimal1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      animal1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string animal1 = 1;</code>
     */
    public Builder clearAnimal1() {
      
      animal1_ = getDefaultInstance().getAnimal1();
      onChanged();
      return this;
    }
    /**
     * <code>string animal1 = 1;</code>
     */
    public Builder setAnimal1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      animal1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object animal2_ = "";
    /**
     * <code>string animal2 = 2;</code>
     */
    public java.lang.String getAnimal2() {
      java.lang.Object ref = animal2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animal2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string animal2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnimal2Bytes() {
      java.lang.Object ref = animal2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animal2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string animal2 = 2;</code>
     */
    public Builder setAnimal2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      animal2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string animal2 = 2;</code>
     */
    public Builder clearAnimal2() {
      
      animal2_ = getDefaultInstance().getAnimal2();
      onChanged();
      return this;
    }
    /**
     * <code>string animal2 = 2;</code>
     */
    public Builder setAnimal2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      animal2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object animal3_ = "";
    /**
     * <code>string animal3 = 3;</code>
     */
    public java.lang.String getAnimal3() {
      java.lang.Object ref = animal3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animal3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string animal3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAnimal3Bytes() {
      java.lang.Object ref = animal3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animal3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string animal3 = 3;</code>
     */
    public Builder setAnimal3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      animal3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string animal3 = 3;</code>
     */
    public Builder clearAnimal3() {
      
      animal3_ = getDefaultInstance().getAnimal3();
      onChanged();
      return this;
    }
    /**
     * <code>string animal3 = 3;</code>
     */
    public Builder setAnimal3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      animal3_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:farm.PriceRequest)
  }

  // @@protoc_insertion_point(class_scope:farm.PriceRequest)
  private static final com.smartfarming.farm.PriceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartfarming.farm.PriceRequest();
  }

  public static com.smartfarming.farm.PriceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceRequest>
      PARSER = new com.google.protobuf.AbstractParser<PriceRequest>() {
    @java.lang.Override
    public PriceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PriceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PriceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartfarming.farm.PriceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

