// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string day = 1;</code>
   */
  java.lang.String getDay();
  /**
   * <code>string day = 1;</code>
   */
  com.google.protobuf.ByteString
      getDayBytes();
}
