// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public interface SwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.SwitchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor = 1;</code>
   */
  java.lang.String getSensor();
  /**
   * <code>string sensor = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
