// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public interface SwitchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.SwitchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string previous = 3;</code>
   */
  java.lang.String getPrevious();
  /**
   * <code>string previous = 3;</code>
   */
  com.google.protobuf.ByteString
      getPreviousBytes();
}
