// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.smartfarming.farm;

public interface WaterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.WaterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 min = 2;</code>
   */
  int getMin();

  /**
   * <code>int32 max = 3;</code>
   */
  int getMax();
}
