// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.smartfarming.farm2;

public interface AnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.AnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string animal = 1;</code>
   */
  java.lang.String getAnimal();
  /**
   * <code>string animal = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnimalBytes();

  /**
   * <code>int32 price = 2;</code>
   */
  int getPrice();
}
