// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.smartfarming.farm2;

public interface AnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.AnimalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 old = 2;</code>
   */
  int getOld();

  /**
   * <code>int32 new = 3;</code>
   */
  int getNew();
}
