// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.smartfarming.farm2;

public interface AreaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.AreaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field = 1;</code>
   */
  java.lang.String getField();
  /**
   * <code>string field = 1;</code>
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <code>int32 width_feet = 2;</code>
   */
  int getWidthFeet();

  /**
   * <code>int32 lengt_feet = 3;</code>
   */
  int getLengtFeet();
}
