// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.smartfarming.farm2;

public interface AreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.AreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field = 2;</code>
   */
  java.lang.String getField();
  /**
   * <code>string field = 2;</code>
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <code>int32 acres = 1;</code>
   */
  int getAcres();
}
