// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.smartfarming.farm2;

public final class FarmServiceImpl2 {
  private FarmServiceImpl2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_AreaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_AreaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_AreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_AreaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_CountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_CountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_CountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_CountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_AnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_AnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_AnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_AnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_WeightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_WeightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_farm_WeightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_farm_WeightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\004farm\"D\n\013AreaRequest\022\r\n" +
      "\005field\030\001 \001(\t\022\022\n\nwidth_feet\030\002 \001(\005\022\022\n\nleng" +
      "t_feet\030\003 \001(\005\",\n\014AreaResponse\022\r\n\005field\030\002 " +
      "\001(\t\022\r\n\005acres\030\001 \001(\005\"0\n\014CountRequest\022\017\n\007an" +
      "imal1\030\001 \001(\t\022\017\n\007animal2\030\002 \001(\t\"\037\n\rCountRes" +
      "ponse\022\016\n\006result\030\001 \001(\005\";\n\016AnimalResponse\022" +
      "\017\n\007message\030\001 \001(\t\022\013\n\003old\030\002 \001(\005\022\013\n\003new\030\003 \001" +
      "(\005\".\n\rAnimalRequest\022\016\n\006animal\030\001 \001(\t\022\r\n\005p" +
      "rice\030\002 \001(\005\"B\n\rWeightRequest\022\017\n\007animal1\030\001" +
      " \001(\t\022\017\n\007animal2\030\002 \001(\t\022\017\n\007animal3\030\003 \001(\t\"." +
      "\n\016WeightResponse\022\014\n\004name\030\002 \001(\t\022\016\n\006weight" +
      "\030\001 \001(\0052\375\001\n\014FarmService2\0228\n\013animalCount\022\022" +
      ".farm.CountRequest\032\023.farm.CountResponse\"" +
      "\000\022>\n\rpriceIncrease\022\023.farm.AnimalRequest\032" +
      "\024.farm.AnimalResponse\"\0000\001\022:\n\tmaxWeight\022\023" +
      ".farm.WeightRequest\032\024.farm.WeightRespons" +
      "e\"\000(\001\0227\n\010areaLand\022\021.farm.AreaRequest\032\022.f" +
      "arm.AreaResponse\"\000(\0010\001B,\n\026com.smartfarmi" +
      "ng.farm2B\020FarmServiceImpl2P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_farm_AreaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_farm_AreaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_AreaRequest_descriptor,
        new java.lang.String[] { "Field", "WidthFeet", "LengtFeet", });
    internal_static_farm_AreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_farm_AreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_AreaResponse_descriptor,
        new java.lang.String[] { "Field", "Acres", });
    internal_static_farm_CountRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_farm_CountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_CountRequest_descriptor,
        new java.lang.String[] { "Animal1", "Animal2", });
    internal_static_farm_CountResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_farm_CountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_CountResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_farm_AnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_farm_AnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_AnimalResponse_descriptor,
        new java.lang.String[] { "Message", "Old", "New", });
    internal_static_farm_AnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_farm_AnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_AnimalRequest_descriptor,
        new java.lang.String[] { "Animal", "Price", });
    internal_static_farm_WeightRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_farm_WeightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_WeightRequest_descriptor,
        new java.lang.String[] { "Animal1", "Animal2", "Animal3", });
    internal_static_farm_WeightResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_farm_WeightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_farm_WeightResponse_descriptor,
        new java.lang.String[] { "Name", "Weight", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
