// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.smartfarming.farm2;

public interface WeightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:farm.WeightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 weight = 1;</code>
   */
  int getWeight();
}
